spring:
  application:
    name: notificacao
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    topic:
      notificacao-usuario: notificacao-usuario
      notificacao-usuario-dlt: notificacao-usuario-dlt
    consumer:
      group-id: notificacao-group
      auto-offset-reset: latest
  datasource:
    url: jdbc:mysql://localhost:3306/api-notificacao?createDatabaseIfNotExist=true
    username: root
    password: root123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.MySQL8Dialect
      jdbc:
        lob:
          non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true